# name: Hello World

# on:
#   workflow_dispatch:

# jobs:
#   say-hello-inline-bash:
#     runs-on: ubuntu-24.04
#     steps:
#       - run: echo "Hello from an inline bash script in a GitHub Action Workflow!"


# name : Hello World

# on :
#   workflow_dispatch:

# jobs:
#   my-first-job:
#     runs-on :  ubuntu-24.04
#     steps : 
#       - run: echo "Hello World"


name : Hello World
on : 
  workflow_dispatch:
jobs : 
  printing-job : 
    runs-on : ubuntu-24.04
    steps : 
      step-1 : 
        - run : echo "My Step 1"
      Step-2 : 
        - run : echo "My step 2"
        - run : echo "THE END"
